// frontend/src/app/shared/components/sidebar/sidebar.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { IconComponent, IconName } from '../icon/icon.component';

interface NavItem {
  to: string;
  label: string;
  icon: IconName;
}

const NAV_ITEMS: NavItem[] = [
  { to: '/dashboard', label: 'Dashboard', icon: 'dashboard' },
  { to: '/employees', label: 'Employees', icon: 'users' },
  { to: '/departments', label: 'Departments', icon: 'building' },
  { to: '/roles', label: 'Roles', icon: 'badge' },
];

@Component({
  selector: 'app-sidebar',
  standalone: true,
  imports: [RouterLink, RouterLinkActive, IconComponent],
  template: `
    @if (open) {
      <div class="sidebar-overlay" (click)="close.emit()"></div>
    }
    <aside class="sidebar" [class.open]="open">
      <div class="sidebar-brand">
        <div class="sidebar-brand-mark">PD</div>
        <div class="sidebar-brand-text">
          <strong>PeopleDesk</strong>
          <span>Employee Management</span>
        </div>
      </div>

      <nav class="sidebar-nav">
        <div class="sidebar-section-label">Workspace</div>
        @for (item of navItems; track item.to) {
          <a
            [routerLink]="item.to"
            routerLinkActive="active"
            class="sidebar-link"
            (click)="close.emit()"
          >
            <app-icon [name]="item.icon" />
            {{ item.label }}
          </a>
        }
      </nav>

      <div class="sidebar-footer">Internal HR Tool · v1.0</div>
    </aside>
  `,
})
export class SidebarComponent {
  @Input() open = false;
  @Output() close = new EventEmitter<void>();

  readonly navItems = NAV_ITEMS;
}

// frontend/src/components/Sidebar.jsx
import { NavLink } from 'react-router-dom';
import { IconDashboard, IconUsers, IconBuilding, IconBadge } from './icons';

const NAV_ITEMS = [
  { to: '/dashboard', label: 'Dashboard', icon: IconDashboard },
  { to: '/employees', label: 'Employees', icon: IconUsers },
  { to: '/departments', label: 'Departments', icon: IconBuilding },
  { to: '/roles', label: 'Roles', icon: IconBadge },
];

export default function Sidebar({ open, onClose }) {
  return (
    <>
      {open && <div className="sidebar-overlay" onClick={onClose} />}
      <aside className={`sidebar ${open ? 'open' : ''}`}>
        <div className="sidebar-brand">
          <div className="sidebar-brand-mark">PD</div>
          <div className="sidebar-brand-text">
            <strong>PeopleDesk</strong>
            <span>Employee Management</span>
          </div>
        </div>

        <nav className="sidebar-nav">
          <div className="sidebar-section-label">Workspace</div>
          {NAV_ITEMS.map(({ to, label, icon: Icon }) => (
            <NavLink
              key={to}
              to={to}
              className={({ isActive }) => `sidebar-link ${isActive ? 'active' : ''}`}
              onClick={onClose}
            >
              <Icon />
              {label}
            </NavLink>
          ))}
        </nav>

        <div className="sidebar-footer">Internal HR Tool · v1.0</div>
      </aside>
    </>
  );
}
